[package]
name = "hibana-quic-examples"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false
autoexamples = false
license = "MIT OR Apache-2.0"

[workspace]
resolver = "3"

[dependencies]
hibana-quic = { path = "..", default-features = false }
hibana-quic-pal = { path = "../pal" }
hibana-tls = { git = "https://github.com/hibanaworks/hibana-tls", rev = "573d9053dca1d9a73e803ad2569f224420b69c3f", default-features = false }
hibana = { git = "https://github.com/hibanaworks/hibana", rev = "6ed1923c9447e48cfd3e4bb0f2d6f12126e2b452", default-features = false }

[[bin]]
name = "hq"
path = "hq/main.rs"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[[test]]
name = "rsa_vectors"
path = "../tests/tls-reference/tests/rsa_vectors.rs"

[[test]]
name = "resumption"
path = "../tests/tls-reference/tests/resumption.rs"

[[test]]
name = "early_tls"
path = "../tests/tls-reference/tests/early_tls.rs"

[[example]]
name = "quic-client"
path = "hello-quic/client.rs"

[[example]]
name = "quic-server"
path = "hello-quic/server.rs"

[[example]]
name = "http3-client"
path = "hello-http3/client.rs"

[[example]]
name = "http3-server"
path = "hello-http3/server.rs"


