[package]
name = "hibana-quic-pico-example"
version = "0.1.0"
edition = "2024"
publish = false
[workspace]
[dependencies]
hibana-quic = { path = "../../..", default-features = false }
hibana = { git = "https://github.com/hibanaworks/hibana", rev = "6ed1923c9447e48cfd3e4bb0f2d6f12126e2b452", default-features = false }
